[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests",]
filterwarnings = ["ignore::PendingDeprecationWarning",
 "ignore::DeprecationWarning"]
addopts = ["--pdbcls=IPython.terminal.debugger:Pdb"]